// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/broker/broker.proto

package broker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProduceRequest struct {
	RoutingKey           string   `protobuf:"bytes,1,opt,name=RoutingKey,proto3" json:"RoutingKey,omitempty"`
	MessageSetSize       uint32   `protobuf:"varint,2,opt,name=MessageSetSize,proto3" json:"MessageSetSize,omitempty"`
	MessageSet           []byte   `protobuf:"bytes,3,opt,name=MessageSet,proto3" json:"MessageSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{0}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

func (m *ProduceRequest) GetMessageSetSize() uint32 {
	if m != nil {
		return m.MessageSetSize
	}
	return 0
}

func (m *ProduceRequest) GetMessageSet() []byte {
	if m != nil {
		return m.MessageSet
	}
	return nil
}

type ProduceResponse struct {
	ErrorCode            uint32   `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{1}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

func (m *ProduceResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ProduceRequest)(nil), "ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "ProduceResponse")
}

func init() { proto.RegisterFile("protos/broker/broker.proto", fileDescriptor_a39eb6806bc9a398) }

var fileDescriptor_a39eb6806bc9a398 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x4f, 0x2a, 0xca, 0xcf, 0x4e, 0x2d, 0x82, 0x52, 0x7a, 0x60, 0x41, 0xa5, 0x0a,
	0x2e, 0xbe, 0x80, 0xa2, 0xfc, 0x94, 0xd2, 0xe4, 0xd4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x39, 0x2e, 0xae, 0xa0, 0xfc, 0xd2, 0x92, 0xcc, 0xbc, 0x74, 0xef, 0xd4, 0x4a, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x24, 0x11, 0x21, 0x35, 0x2e, 0x3e, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4,
	0xf4, 0xd4, 0xe0, 0xd4, 0x92, 0xe0, 0xcc, 0xaa, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xde, 0x20,
	0x34, 0x51, 0x90, 0x39, 0x08, 0x11, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x24, 0x11, 0x25,
	0x7d, 0x2e, 0x7e, 0xb8, 0xcd, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x32, 0x5c, 0x9c, 0xae,
	0x45, 0x45, 0xf9, 0x45, 0xce, 0xf9, 0x29, 0xa9, 0x60, 0x9b, 0x79, 0x83, 0x10, 0x02, 0x46, 0x56,
	0x5c, 0x5c, 0x50, 0x0d, 0x8e, 0x01, 0x9e, 0x42, 0x3a, 0x5c, 0xec, 0x50, 0x9e, 0x10, 0xbf, 0x1e,
	0xaa, 0x17, 0xa4, 0x04, 0xf4, 0xd0, 0x4c, 0x4e, 0x62, 0x03, 0xfb, 0xd6, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x48, 0xca, 0x33, 0x1f, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProduceAPIClient is the client API for ProduceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProduceAPIClient interface {
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
}

type produceAPIClient struct {
	cc *grpc.ClientConn
}

func NewProduceAPIClient(cc *grpc.ClientConn) ProduceAPIClient {
	return &produceAPIClient{cc}
}

func (c *produceAPIClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, "/ProduceAPI/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProduceAPIServer is the server API for ProduceAPI service.
type ProduceAPIServer interface {
	Produce(context.Context, *ProduceRequest) (*ProduceResponse, error)
}

// UnimplementedProduceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedProduceAPIServer struct {
}

func (*UnimplementedProduceAPIServer) Produce(ctx context.Context, req *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}

func RegisterProduceAPIServer(s *grpc.Server, srv ProduceAPIServer) {
	s.RegisterService(&_ProduceAPI_serviceDesc, srv)
}

func _ProduceAPI_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProduceAPIServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProduceAPI/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProduceAPIServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProduceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProduceAPI",
	HandlerType: (*ProduceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _ProduceAPI_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/broker/broker.proto",
}
