// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/broker/broker.proto

package broker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BindQueueRequest struct {
	ExchangeName         string   `protobuf:"bytes,1,opt,name=ExchangeName,proto3" json:"ExchangeName,omitempty"`
	QueueName            string   `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindQueueRequest) Reset()         { *m = BindQueueRequest{} }
func (m *BindQueueRequest) String() string { return proto.CompactTextString(m) }
func (*BindQueueRequest) ProtoMessage()    {}
func (*BindQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{0}
}

func (m *BindQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindQueueRequest.Unmarshal(m, b)
}
func (m *BindQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindQueueRequest.Marshal(b, m, deterministic)
}
func (m *BindQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindQueueRequest.Merge(m, src)
}
func (m *BindQueueRequest) XXX_Size() int {
	return xxx_messageInfo_BindQueueRequest.Size(m)
}
func (m *BindQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindQueueRequest proto.InternalMessageInfo

func (m *BindQueueRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *BindQueueRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

type BindQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindQueueResponse) Reset()         { *m = BindQueueResponse{} }
func (m *BindQueueResponse) String() string { return proto.CompactTextString(m) }
func (*BindQueueResponse) ProtoMessage()    {}
func (*BindQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{1}
}

func (m *BindQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindQueueResponse.Unmarshal(m, b)
}
func (m *BindQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindQueueResponse.Marshal(b, m, deterministic)
}
func (m *BindQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindQueueResponse.Merge(m, src)
}
func (m *BindQueueResponse) XXX_Size() int {
	return xxx_messageInfo_BindQueueResponse.Size(m)
}
func (m *BindQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindQueueResponse proto.InternalMessageInfo

type CreateExchangeRequest struct {
	ExchangeName         string   `protobuf:"bytes,1,opt,name=ExchangeName,proto3" json:"ExchangeName,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExchangeRequest) Reset()         { *m = CreateExchangeRequest{} }
func (m *CreateExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeRequest) ProtoMessage()    {}
func (*CreateExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{2}
}

func (m *CreateExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeRequest.Unmarshal(m, b)
}
func (m *CreateExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeRequest.Marshal(b, m, deterministic)
}
func (m *CreateExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeRequest.Merge(m, src)
}
func (m *CreateExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeRequest.Size(m)
}
func (m *CreateExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeRequest proto.InternalMessageInfo

func (m *CreateExchangeRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *CreateExchangeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CreateExchangeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateExchangeResponse) Reset()         { *m = CreateExchangeResponse{} }
func (m *CreateExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateExchangeResponse) ProtoMessage()    {}
func (*CreateExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{3}
}

func (m *CreateExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateExchangeResponse.Unmarshal(m, b)
}
func (m *CreateExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateExchangeResponse.Marshal(b, m, deterministic)
}
func (m *CreateExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateExchangeResponse.Merge(m, src)
}
func (m *CreateExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateExchangeResponse.Size(m)
}
func (m *CreateExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateExchangeResponse proto.InternalMessageInfo

type CreateQueueRequest struct {
	ExchangeName         string   `protobuf:"bytes,1,opt,name=ExchangeName,proto3" json:"ExchangeName,omitempty"`
	QueueName            string   `protobuf:"bytes,2,opt,name=QueueName,proto3" json:"QueueName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQueueRequest) Reset()         { *m = CreateQueueRequest{} }
func (m *CreateQueueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateQueueRequest) ProtoMessage()    {}
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{4}
}

func (m *CreateQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueRequest.Unmarshal(m, b)
}
func (m *CreateQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueRequest.Marshal(b, m, deterministic)
}
func (m *CreateQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueRequest.Merge(m, src)
}
func (m *CreateQueueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateQueueRequest.Size(m)
}
func (m *CreateQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueRequest proto.InternalMessageInfo

func (m *CreateQueueRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *CreateQueueRequest) GetQueueName() string {
	if m != nil {
		return m.QueueName
	}
	return ""
}

type CreateQueueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateQueueResponse) Reset()         { *m = CreateQueueResponse{} }
func (m *CreateQueueResponse) String() string { return proto.CompactTextString(m) }
func (*CreateQueueResponse) ProtoMessage()    {}
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{5}
}

func (m *CreateQueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateQueueResponse.Unmarshal(m, b)
}
func (m *CreateQueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateQueueResponse.Marshal(b, m, deterministic)
}
func (m *CreateQueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateQueueResponse.Merge(m, src)
}
func (m *CreateQueueResponse) XXX_Size() int {
	return xxx_messageInfo_CreateQueueResponse.Size(m)
}
func (m *CreateQueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateQueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateQueueResponse proto.InternalMessageInfo

type ProduceRequest struct {
	StreamName           string   `protobuf:"bytes,1,opt,name=StreamName,proto3" json:"StreamName,omitempty"`
	MessageSetSize       uint32   `protobuf:"varint,2,opt,name=MessageSetSize,proto3" json:"MessageSetSize,omitempty"`
	MessageSet           []byte   `protobuf:"bytes,3,opt,name=MessageSet,proto3" json:"MessageSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{6}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetStreamName() string {
	if m != nil {
		return m.StreamName
	}
	return ""
}

func (m *ProduceRequest) GetMessageSetSize() uint32 {
	if m != nil {
		return m.MessageSetSize
	}
	return 0
}

func (m *ProduceRequest) GetMessageSet() []byte {
	if m != nil {
		return m.MessageSet
	}
	return nil
}

type ProduceResponse struct {
	ErrorCode            uint32   `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a39eb6806bc9a398, []int{7}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

func (m *ProduceResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*BindQueueRequest)(nil), "BindQueueRequest")
	proto.RegisterType((*BindQueueResponse)(nil), "BindQueueResponse")
	proto.RegisterType((*CreateExchangeRequest)(nil), "CreateExchangeRequest")
	proto.RegisterType((*CreateExchangeResponse)(nil), "CreateExchangeResponse")
	proto.RegisterType((*CreateQueueRequest)(nil), "CreateQueueRequest")
	proto.RegisterType((*CreateQueueResponse)(nil), "CreateQueueResponse")
	proto.RegisterType((*ProduceRequest)(nil), "ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "ProduceResponse")
}

func init() { proto.RegisterFile("protos/broker/broker.proto", fileDescriptor_a39eb6806bc9a398) }

var fileDescriptor_a39eb6806bc9a398 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0x8a, 0xd0, 0xb1, 0x5f, 0x4e, 0x6c, 0x0d, 0x41, 0xa4, 0xec, 0x41, 0x7a, 0xda,
	0x82, 0xbd, 0x78, 0xad, 0xa5, 0x07, 0x0f, 0x6a, 0x4d, 0x8a, 0xf7, 0xb4, 0x19, 0x6a, 0x91, 0x66,
	0xe3, 0x6e, 0x02, 0xd5, 0x1f, 0xe7, 0x6f, 0x93, 0x6e, 0xd2, 0x7c, 0x99, 0x8b, 0xe0, 0x29, 0xe1,
	0xc9, 0xce, 0xfb, 0x64, 0xde, 0x04, 0xec, 0x50, 0x8a, 0x48, 0xa8, 0xd1, 0x52, 0x8a, 0x77, 0x92,
	0xe9, 0x85, 0x6b, 0xc8, 0x16, 0xd0, 0xbd, 0xdf, 0x04, 0xfe, 0x4b, 0x4c, 0x31, 0x39, 0xf4, 0x11,
	0x93, 0x8a, 0x90, 0x41, 0x73, 0xb6, 0x5b, 0xbd, 0x79, 0xc1, 0x9a, 0x9e, 0xbc, 0x2d, 0x59, 0xc6,
	0xc0, 0x18, 0x36, 0x9c, 0x12, 0xc3, 0x2b, 0x68, 0xe8, 0x19, 0x7d, 0xe0, 0x48, 0x1f, 0xc8, 0x01,
	0x33, 0xe1, 0xbc, 0x90, 0xaa, 0x42, 0x11, 0x28, 0x62, 0xcf, 0xd0, 0x9b, 0x4a, 0xf2, 0x22, 0x3a,
	0x04, 0xfd, 0xc5, 0x87, 0x70, 0xb2, 0xf8, 0x0c, 0x0f, 0x2a, 0x7d, 0xcf, 0x2c, 0xe8, 0x57, 0x03,
	0x53, 0xd5, 0x2b, 0x60, 0xf2, 0xe4, 0x9f, 0xf7, 0xea, 0x81, 0x59, 0xca, 0x4d, 0x75, 0x3b, 0x68,
	0xcf, 0xa5, 0xf0, 0xe3, 0x55, 0xa6, 0xba, 0x06, 0x70, 0x23, 0x49, 0xde, 0xb6, 0x20, 0x2a, 0x10,
	0xbc, 0x81, 0xf6, 0x23, 0x29, 0xe5, 0xad, 0xc9, 0xa5, 0xc8, 0xdd, 0x7c, 0x25, 0xae, 0x96, 0x53,
	0xa1, 0xfb, 0x9c, 0x9c, 0x58, 0xc7, 0x03, 0x63, 0xd8, 0x74, 0x0a, 0x84, 0x8d, 0xa0, 0x93, 0x99,
	0x93, 0x97, 0xd9, 0x6f, 0x30, 0x93, 0x52, 0xc8, 0xa9, 0xf0, 0x13, 0x73, 0xcb, 0xc9, 0xc1, 0xed,
	0xb7, 0x01, 0x90, 0x4e, 0x4c, 0xe6, 0x0f, 0x38, 0x81, 0x76, 0xb9, 0x42, 0xec, 0xf3, 0xda, 0x8f,
	0x64, 0x5f, 0xf2, 0xfa, 0xae, 0xf1, 0x0e, 0xce, 0x0a, 0x9d, 0xa0, 0xc9, 0x7f, 0x37, 0x6f, 0x5f,
	0xf0, 0x9a, 0xda, 0x70, 0x9c, 0xd5, 0x96, 0x6e, 0x84, 0x1d, 0x5e, 0xee, 0xd1, 0xee, 0xf2, 0xca,
	0x7a, 0xcb, 0x53, 0xfd, 0xdf, 0x8e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x40, 0x28, 0x8b, 0xdd,
	0xd5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProduceAPIClient is the client API for ProduceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProduceAPIClient interface {
	CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error)
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	ProduceMessage(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
}

type produceAPIClient struct {
	cc *grpc.ClientConn
}

func NewProduceAPIClient(cc *grpc.ClientConn) ProduceAPIClient {
	return &produceAPIClient{cc}
}

func (c *produceAPIClient) CreateExchange(ctx context.Context, in *CreateExchangeRequest, opts ...grpc.CallOption) (*CreateExchangeResponse, error) {
	out := new(CreateExchangeResponse)
	err := c.cc.Invoke(ctx, "/ProduceAPI/CreateExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *produceAPIClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, "/ProduceAPI/CreateQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *produceAPIClient) ProduceMessage(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, "/ProduceAPI/ProduceMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProduceAPIServer is the server API for ProduceAPI service.
type ProduceAPIServer interface {
	CreateExchange(context.Context, *CreateExchangeRequest) (*CreateExchangeResponse, error)
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	ProduceMessage(context.Context, *ProduceRequest) (*ProduceResponse, error)
}

// UnimplementedProduceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedProduceAPIServer struct {
}

func (*UnimplementedProduceAPIServer) CreateExchange(ctx context.Context, req *CreateExchangeRequest) (*CreateExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExchange not implemented")
}
func (*UnimplementedProduceAPIServer) CreateQueue(ctx context.Context, req *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (*UnimplementedProduceAPIServer) ProduceMessage(ctx context.Context, req *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceMessage not implemented")
}

func RegisterProduceAPIServer(s *grpc.Server, srv ProduceAPIServer) {
	s.RegisterService(&_ProduceAPI_serviceDesc, srv)
}

func _ProduceAPI_CreateExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProduceAPIServer).CreateExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProduceAPI/CreateExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProduceAPIServer).CreateExchange(ctx, req.(*CreateExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProduceAPI_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProduceAPIServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProduceAPI/CreateQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProduceAPIServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProduceAPI_ProduceMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProduceAPIServer).ProduceMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProduceAPI/ProduceMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProduceAPIServer).ProduceMessage(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProduceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProduceAPI",
	HandlerType: (*ProduceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExchange",
			Handler:    _ProduceAPI_CreateExchange_Handler,
		},
		{
			MethodName: "CreateQueue",
			Handler:    _ProduceAPI_CreateQueue_Handler,
		},
		{
			MethodName: "ProduceMessage",
			Handler:    _ProduceAPI_ProduceMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/broker/broker.proto",
}
