// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/broker.proto

package broker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProduceRequest struct {
	RequiredAcks         int32    `protobuf:"zigzag32,1,opt,name=RequiredAcks,proto3" json:"RequiredAcks,omitempty"`
	Timeout              uint32   `protobuf:"varint,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	TopicName            string   `protobuf:"bytes,3,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	Partition            uint32   `protobuf:"varint,4,opt,name=Partition,proto3" json:"Partition,omitempty"`
	MessageSetSize       uint32   `protobuf:"varint,5,opt,name=MessageSetSize,proto3" json:"MessageSetSize,omitempty"`
	MessageSet           []byte   `protobuf:"bytes,6,opt,name=MessageSet,proto3" json:"MessageSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe7e04b73854ec, []int{0}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetRequiredAcks() int32 {
	if m != nil {
		return m.RequiredAcks
	}
	return 0
}

func (m *ProduceRequest) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *ProduceRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ProduceRequest) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ProduceRequest) GetMessageSetSize() uint32 {
	if m != nil {
		return m.MessageSetSize
	}
	return 0
}

func (m *ProduceRequest) GetMessageSet() []byte {
	if m != nil {
		return m.MessageSet
	}
	return nil
}

type ProduceResponse struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	Partition            uint32   `protobuf:"varint,2,opt,name=Partition,proto3" json:"Partition,omitempty"`
	ErrorCode            uint32   `protobuf:"varint,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Offset               uint64   `protobuf:"varint,4,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe7e04b73854ec, []int{1}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

func (m *ProduceResponse) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ProduceResponse) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ProduceResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ProduceResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Request struct {
	ApiKey               int32    `protobuf:"varint,1,opt,name=ApiKey,proto3" json:"ApiKey,omitempty"`
	ApiVersion           int32    `protobuf:"varint,2,opt,name=ApiVersion,proto3" json:"ApiVersion,omitempty"`
	CorrelationId        int32    `protobuf:"varint,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	ClientId             string   `protobuf:"bytes,4,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe7e04b73854ec, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetApiKey() int32 {
	if m != nil {
		return m.ApiKey
	}
	return 0
}

func (m *Request) GetApiVersion() int32 {
	if m != nil {
		return m.ApiVersion
	}
	return 0
}

func (m *Request) GetCorrelationId() int32 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func (m *Request) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type Response struct {
	CorrelationId        int32    `protobuf:"varint,3,opt,name=CorrelationId,proto3" json:"CorrelationId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe7e04b73854ec, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCorrelationId() int32 {
	if m != nil {
		return m.CorrelationId
	}
	return 0
}

func init() {
	proto.RegisterType((*ProduceRequest)(nil), "ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "ProduceResponse")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("api/broker.proto", fileDescriptor_e4fe7e04b73854ec) }

var fileDescriptor_e4fe7e04b73854ec = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0x99, 0xbe, 0x4d, 0xda, 0x5c, 0xfa, 0xf5, 0xce, 0xa2, 0x0c, 0xa5, 0x48, 0x08, 0x22,
	0x59, 0x48, 0x15, 0xdd, 0xb9, 0x0b, 0xc5, 0x45, 0x11, 0xb5, 0x4c, 0x8b, 0xfb, 0xb4, 0xb9, 0x95,
	0xa1, 0x1f, 0x13, 0x67, 0xa6, 0x0b, 0xdd, 0xfa, 0x0f, 0xfd, 0x45, 0x92, 0x31, 0x6d, 0x9a, 0x2c,
	0xc4, 0x5d, 0xce, 0x93, 0x99, 0xb9, 0xe7, 0x1c, 0x2e, 0xf4, 0xe2, 0x54, 0x5c, 0x2d, 0x94, 0x5c,
	0xa3, 0x1a, 0xa5, 0x4a, 0x1a, 0x19, 0x7c, 0x11, 0xe8, 0x4c, 0x95, 0x4c, 0xf6, 0x4b, 0xe4, 0xf8,
	0xb6, 0x47, 0x6d, 0x68, 0x00, 0xad, 0xec, 0x53, 0x28, 0x4c, 0xa2, 0xe5, 0x5a, 0x33, 0xe2, 0x93,
	0xf0, 0x3f, 0x2f, 0x31, 0xca, 0xa0, 0x31, 0x17, 0x5b, 0x94, 0x7b, 0xc3, 0x6a, 0x3e, 0x09, 0xdb,
	0xfc, 0x20, 0xe9, 0x10, 0xbc, 0xb9, 0x4c, 0xc5, 0xf2, 0x29, 0xde, 0x22, 0xfb, 0xe7, 0x93, 0xd0,
	0xe3, 0x05, 0xc8, 0xfe, 0x4e, 0x63, 0x65, 0x84, 0x11, 0x72, 0xc7, 0xea, 0xf6, 0x66, 0x01, 0xe8,
	0x05, 0x74, 0x1e, 0x51, 0xeb, 0xf8, 0x15, 0x67, 0x68, 0x66, 0xe2, 0x03, 0x99, 0x63, 0x8f, 0x54,
	0x28, 0x3d, 0x03, 0x28, 0x08, 0x73, 0x7d, 0x12, 0xb6, 0xf8, 0x09, 0x09, 0x3e, 0x09, 0x74, 0x8f,
	0xa1, 0x74, 0x2a, 0x77, 0x1a, 0xcb, 0xbe, 0xc8, 0xaf, 0xbe, 0x6a, 0x55, 0x5f, 0x43, 0xf0, 0xee,
	0x95, 0x92, 0x6a, 0x2c, 0x93, 0x9f, 0x4c, 0x6d, 0x5e, 0x00, 0xda, 0x07, 0xf7, 0x79, 0xb5, 0xd2,
	0x68, 0x6c, 0xa0, 0x3a, 0xcf, 0x55, 0xe6, 0xa2, 0x71, 0xe8, 0xb4, 0x0f, 0x6e, 0x94, 0x8a, 0x07,
	0x7c, 0xb7, 0xa3, 0x1d, 0x9e, 0xab, 0x2c, 0x49, 0x94, 0x8a, 0x17, 0x54, 0xfa, 0x30, 0xd8, 0xe1,
	0x27, 0x84, 0x9e, 0x43, 0x7b, 0x2c, 0x95, 0xc2, 0x4d, 0x9c, 0x19, 0x99, 0x24, 0x76, 0xba, 0xc3,
	0xcb, 0x90, 0x0e, 0xa0, 0x39, 0xde, 0x08, 0xdc, 0x99, 0x49, 0x62, 0x3d, 0x78, 0xfc, 0xa8, 0x83,
	0x6b, 0x68, 0x1e, 0x3b, 0xf8, 0xd3, 0x6b, 0x37, 0x77, 0x00, 0x79, 0x79, 0xd1, 0x74, 0x42, 0x2f,
	0xa1, 0x91, 0x2b, 0xda, 0x1d, 0x95, 0x37, 0x65, 0xd0, 0x1b, 0x55, 0x5a, 0x5e, 0xb8, 0x76, 0xab,
	0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x6b, 0xea, 0x41, 0x69, 0x02, 0x00, 0x00,
}
